## Problem 2 - Data manipulation and selection (*4 points*)

In this problem you will clean the data from our data file by removing no-data values, convert temperature values in Fahrenheit to Celsius, and split the data into separate datasets using the weather station identification code. We will start this problem by cleaning and converting our temperature data. Please perform the tasks below by writing your code into the codeblocks in each section.

**Notice**: Closely follow the instructions! For example, you should be sure to use **exactly** the same variable names mentioned in the instructions because your answers will be automatically graded, and the tests that grade your answers rely on following the same formatting or variable naming as in the instructions.

**Your score on this problem will be based on following criteria:**

- Creating a new dataframe called `selected` that contains select columns from the data file
- Cleaning the new dataframe by removing no-data values
- Creating a new column for temperatures converted from Fahrenheit to Celsius
- Dividing the data into separate dataframes for the Helsinki Kumpula and Rovaniemi stations
- Saving the new dataframes to CSV files
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook and data files to your GitHub repository for this week's exercise  

### Part 1 (*0 points*)

The first step for this problem is to read the data file `6153237444115dat.csv` again into a variable `data` using Pandas. Remember to specify the no-data values (you can copy your code from Problem 1).

In [1]:
# Import pandas
import pandas as pd

In [4]:
pwd

'C:\\Users\\BGP001\\Peter\\Lesson_5\\exercise-5-okonwuchekwa9'

In [5]:
cd data

C:\Users\BGP001\Peter\Lesson_5\exercise-5-okonwuchekwa9\data


In [6]:
#data = None
# Define file path
fp = '6153237444115dat.csv'
#Read in data from the file
data = pd.read_csv(fp, na_values=['*', '**', '***', '****', '*****', '******'])
#temp_data = pd.read_csv('kumpula-june-2016-w-metadata.txt', skiprows=8, usecols=['YEARMODA', 'TEMP'])


Check that the first rows of the DataFrame look ok: 

In [7]:
# Row check
data.head()

USAF   WBAN  YR--MODAHRMN    DIR   SPD   GUS  CLG  SKC   L   M  ...  \
0  28450  99999  201705010000  174.0  10.0  14.0  NaN  NaN NaN NaN  ...   
1  28450  99999  201705010020  180.0  10.0   NaN  4.0  NaN NaN NaN  ...   
2  28450  99999  201705010050  190.0  10.0   NaN  4.0  NaN NaN NaN  ...   
3  28450  99999  201705010100  188.0  12.0  16.0  NaN  NaN NaN NaN  ...   
4  28450  99999  201705010120  200.0  13.0   NaN  2.0  OBS NaN NaN  ...   

      SLP    ALT    STP  MAX  MIN  PCP01  PCP06  PCP24  PCPXX    SD  
0  1009.2    NaN  984.1  NaN  NaN    NaN    NaN    NaN    NaN  35.0  
1     NaN  29.74    NaN  NaN  NaN    NaN    NaN    NaN    NaN   NaN  
2     NaN  29.74    NaN  NaN  NaN    NaN    NaN    NaN    NaN   NaN  
3  1009.1    NaN  984.0  NaN  NaN    NaN    NaN    NaN    NaN  35.0  
4     NaN  29.74    NaN  NaN  NaN    NaN    NaN    NaN    NaN   NaN  

[5 rows x 33 columns]

Check the number of rows in the DataFrame:

In [8]:
#check no of rows
data.shape

(11694, 33)

### Part 2 (*1 point*)

Next, your task is to subset the data and remove rows with missing temperature values.

 - Select the columns `USAF`, `YR--MODAHRMN`, `TEMP`, `MAX`, and `MIN` from the `data` dataframe and assign them to the variable `selected`
 - Remove all rows from `selected` that have NoData in the column `TEMP` using the `dropna()` function

In [10]:
selected = pd.read_csv(fp, na_values=['*', '**', '***', '****', '*****', '******'], usecols=['USAF','YR--MODAHRMN','TEMP','MAX','MIN'])

# YOUR CODE HERE
#temp_data = pd.read_csv('kumpula-june-2016-w-metadata.txt', skiprows=8, usecols=['YEARMODA', 'TEMP'])

Check that you selected the correct column names:

In [11]:
selected.head()

USAF  YR--MODAHRMN  TEMP  MAX  MIN
0  28450  201705010000  31.0  NaN  NaN
1  28450  201705010020  30.0  NaN  NaN
2  28450  201705010050  30.0  NaN  NaN
3  28450  201705010100  31.0  NaN  NaN
4  28450  201705010120  30.0  NaN  NaN

Check how many rows you have after removing the no-data values:

In [14]:
selected = selected.dropna(subset=['TEMP'])

In [15]:
selected

USAF  YR--MODAHRMN  TEMP  MAX  MIN
0      28450  201705010000  31.0  NaN  NaN
1      28450  201705010020  30.0  NaN  NaN
2      28450  201705010050  30.0  NaN  NaN
3      28450  201705010100  31.0  NaN  NaN
4      28450  201705010120  30.0  NaN  NaN
...      ...           ...   ...  ...  ...
11689  29980  201708311900  64.0  NaN  NaN
11690  29980  201708312000  64.0  NaN  NaN
11691  29980  201708312100  64.0  NaN  NaN
11692  29980  201708312200  64.0  NaN  NaN
11693  29980  201708312300  64.0  NaN  NaN

[11691 rows x 5 columns]

In [16]:
len(selected)

11691

### Part 3 (*1 point*)

Next, you can convert the temperature values in Fahrenheit to Celsius.

- Create a new column in `selected` called `Celsius`
- Convert the Fahrenheit temperatures from `TEMP` using the conversion formula (below) and store the results in the new `Celsius`column.

$$
\Large
\begin{equation}
  T_{\mathrm{Celsius}} = (T_{\mathrm{Fahrenheit}} - 32)~/~1.8
\end{equation}
$$

- Round the values in the `Celsius` column to have 0 decimals (**do not** create a new column, update the current one)
- Convert the `Celsius` values into integers (**do not** create a new column, update the current one)

In [17]:
# YOUR CODE HERE
# creat a new column and convert temp fahrenheit to celsius
selected["Celsius"] = (selected["TEMP"]-32) / 1.8

In [18]:
# Check your dataframe
selected.head()

USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  28450  201705010000  31.0  NaN  NaN -0.555556
1  28450  201705010020  30.0  NaN  NaN -1.111111
2  28450  201705010050  30.0  NaN  NaN -1.111111
3  28450  201705010100  31.0  NaN  NaN -0.555556
4  28450  201705010120  30.0  NaN  NaN -1.111111

In [19]:
# Check data types
print(selected.dtypes)

USAF              int64
YR--MODAHRMN      int64
TEMP            float64
MAX             float64
MIN             float64
Celsius         float64
dtype: object


### Part 4 (*1 point*)

Your next task is to divide `selected` into two separate dataframes. Please use the given variable names and write your answer to the codeblock below.

- Select all rows from the `selected` DataFrame with the `USAF` code `29980` into a variable called `kumpula`
- Select all rows from the `selected` DataFrame with the `USAF` code `28450` into a variable called `rovaniemi`

In [20]:
selected

USAF  YR--MODAHRMN  TEMP  MAX  MIN    Celsius
0      28450  201705010000  31.0  NaN  NaN  -0.555556
1      28450  201705010020  30.0  NaN  NaN  -1.111111
2      28450  201705010050  30.0  NaN  NaN  -1.111111
3      28450  201705010100  31.0  NaN  NaN  -0.555556
4      28450  201705010120  30.0  NaN  NaN  -1.111111
...      ...           ...   ...  ...  ...        ...
11689  29980  201708311900  64.0  NaN  NaN  17.777778
11690  29980  201708312000  64.0  NaN  NaN  17.777778
11691  29980  201708312100  64.0  NaN  NaN  17.777778
11692  29980  201708312200  64.0  NaN  NaN  17.777778
11693  29980  201708312300  64.0  NaN  NaN  17.777778

[11691 rows x 6 columns]

In [30]:
selected.head()

USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  29980  201705010000  31.0  NaN  NaN -0.555556
1  29980  201705010020  30.0  NaN  NaN -1.111111
2  29980  201705010050  30.0  NaN  NaN -1.111111
3  29980  201705010100  31.0  NaN  NaN -0.555556
4  29980  201705010120  30.0  NaN  NaN -1.111111

In [32]:
selected.tail()

USAF  YR--MODAHRMN  TEMP  MAX  MIN    Celsius
11689  29980  201708311900  64.0  NaN  NaN  17.777778
11690  29980  201708312000  64.0  NaN  NaN  17.777778
11691  29980  201708312100  64.0  NaN  NaN  17.777778
11692  29980  201708312200  64.0  NaN  NaN  17.777778
11693  29980  201708312300  64.0  NaN  NaN  17.777778

In [50]:
kumpula = selected.loc[0:8769]

In [51]:
type(kumpula)

pandas.core.frame.DataFrame

In [33]:
rovaniemi = selected.loc[8770:11693]

In [24]:
kumpula = selected['USAF'] >= 28450
rovaniemi = selected['USAF'] >= 29980

# YOUR CODE HERE

In [52]:
kumpula

USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0     29980  201705010000  31.0  NaN  NaN -0.555556
1     29980  201705010020  30.0  NaN  NaN -1.111111
2     29980  201705010050  30.0  NaN  NaN -1.111111
3     29980  201705010100  31.0  NaN  NaN -0.555556
4     29980  201705010120  30.0  NaN  NaN -1.111111
...     ...           ...   ...  ...  ...       ...
8765  29980  201708312220  46.0  NaN  NaN  7.777778
8766  29980  201708312250  46.0  NaN  NaN  7.777778
8767  29980  201708312300  48.0  NaN  NaN  8.888889
8768  29980  201708312320  46.0  NaN  NaN  7.777778
8769  29980  201708312350  48.0  NaN  NaN  8.888889

[8767 rows x 6 columns]

In [35]:
rovaniemi

USAF  YR--MODAHRMN  TEMP  MAX  MIN    Celsius
8770   29980  201705010000  37.0  NaN  NaN   2.777778
8771   29980  201705010100  37.0  NaN  NaN   2.777778
8772   29980  201705010200  37.0  NaN  NaN   2.777778
8773   29980  201705010300  37.0  NaN  NaN   2.777778
8774   29980  201705010400  39.0  NaN  NaN   3.888889
...      ...           ...   ...  ...  ...        ...
11689  29980  201708311900  64.0  NaN  NaN  17.777778
11690  29980  201708312000  64.0  NaN  NaN  17.777778
11691  29980  201708312100  64.0  NaN  NaN  17.777778
11692  29980  201708312200  64.0  NaN  NaN  17.777778
11693  29980  201708312300  64.0  NaN  NaN  17.777778

[2924 rows x 6 columns]

In [36]:
# Check the dataframe
print("Kumpula: \n", kumpula.head(), "\n")

Kumpula: 
     USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  29980  201705010000  31.0  NaN  NaN -0.555556
1  29980  201705010020  30.0  NaN  NaN -1.111111
2  29980  201705010050  30.0  NaN  NaN -1.111111
3  29980  201705010100  31.0  NaN  NaN -0.555556
4  29980  201705010120  30.0  NaN  NaN -1.111111 



In [54]:
type(kumpula)

pandas.core.frame.DataFrame

In [48]:
type(rovaniemi)

pandas.core.frame.DataFrame

In [37]:
rovaniemi

USAF  YR--MODAHRMN  TEMP  MAX  MIN    Celsius
8770   29980  201705010000  37.0  NaN  NaN   2.777778
8771   29980  201705010100  37.0  NaN  NaN   2.777778
8772   29980  201705010200  37.0  NaN  NaN   2.777778
8773   29980  201705010300  37.0  NaN  NaN   2.777778
8774   29980  201705010400  39.0  NaN  NaN   3.888889
...      ...           ...   ...  ...  ...        ...
11689  29980  201708311900  64.0  NaN  NaN  17.777778
11690  29980  201708312000  64.0  NaN  NaN  17.777778
11691  29980  201708312100  64.0  NaN  NaN  17.777778
11692  29980  201708312200  64.0  NaN  NaN  17.777778
11693  29980  201708312300  64.0  NaN  NaN  17.777778

[2924 rows x 6 columns]

In [38]:
# Check the dataframe
print("Rovaniemi: \n", rovaniemi.head(), "\n")

Rovaniemi: 
        USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
8770  29980  201705010000  37.0  NaN  NaN  2.777778
8771  29980  201705010100  37.0  NaN  NaN  2.777778
8772  29980  201705010200  37.0  NaN  NaN  2.777778
8773  29980  201705010300  37.0  NaN  NaN  2.777778
8774  29980  201705010400  39.0  NaN  NaN  3.888889 



### Part 5 (*1 point*)

Now you can save your selections to csv files.

- Save the `kumpula` DataFrame into the file `Kumpula_temps_May_Aug_2017.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Save the `rovaniemi` DataFrame into the file `Rovaniemi_temps_May_Aug_2017.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Remember to commit both data files to your Exercise 5 repository

In [ ]:
#output_fp2 = "Kumpula_temps_above15_June_2016.csv"
#warm_temp1.to_csv(output_fp2, sep=",", index=False, float_format="%.1f")

In [55]:
# YOUR CODE HERE
output_fp = "Kumpula_temps_May_Aug_2017.csv"
kumpula.to_csv(output_fp, sep=",", float_format="%.2f")

In [56]:
pwd

'C:\\Users\\BGP001\\Peter\\Lesson_5\\exercise-5-okonwuchekwa9\\data'

In [58]:
output_fp2 = "Rovaniemi_temps_May_Aug_2017.csv"
rovaniemi.to_csv(output_fp2, sep=",", float_format="%.2f")

In [ ]:
#Read-only cell for hidden tests :)

### Problem 2 summary

- Was anything unclear to you in Problem 2?
- Did you encounter any problems with decimal formatting?

Also, make sure you:

- Check that your code includes informative comments explaining what your code does
- Commit and push your changes to your GitHub repository for Exercise 5 (including your 2 new data files)

Please write your answers and comments below (**activate the cell by double clicking**):

YOUR ANSWER HERE

### On to Problem 3

Now you can continue to [Problem 3: Data analysis](Exercise-5-problem-3.ipynb)